GOOGLE_API_KEY = "AQ.Ab8RN6ITtPuh734GwMFAQeTD2AT2CU4iVVi-QWjK10mZeBgoUw"
DEEPSEEK_API_KEY = "sk-145017311b6644ec91a01208b8857f99"
OPENAI_API_KEY = "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"
GROQ_API_KEY = "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"
KIMI_API_KEY = "sk-hsuF8zW8lLpknTUYbNsc0WdT22YKszA8OjQhLM8EOZDwUPLV"
CEREBRAS_API_KEY = "csk-err8ke8jtvj552j394kxerfhpkvk4eewc68fj3tkty24x2x5"
MISTRAL_API_KEY = "MxDCwjXmuOqMBSlH6r3DT40Xbgz7W88K"
COHERE_API_KEY = "cohere_5Rgp8694GfTHvxIMLAOWtoChXsC4PaBNTy11uIhV1stmdE"
AI21_API_KEY = "150e2225-6986-4475-8e27-6397def8dc4e"
CHATBOT_PASSWORD = "camacol2024"
LIVO_GOOGLE_SHEETS_URL = "https://docs.google.com/spreadsheets/d/1us9foQLfuyKz1vPOUBFL1Y1WsYxTaQSl/edit?usp=sharing&ouid=108359182095255841960&rtpof=true&sd=true"
